export const transactions = [
  {
    _id: 'transaction1',
    name: 'Spotify',
    paymentChannel: 'card',
    type: 'debit',
    amount: 15,
    status: 'processing',
    date: 'Wed 1:00pm',
    category: 'subscription',
    accountId: 'checking1',
  },
  {
    _id: 'transaction2',
    name: 'Alexa Doe',
    paymentChannel: 'Bank Transfer',
    type: 'credit',
    amount: 100,
    status: 'success',
    date: 'Tue 3:00pm',
    category: 'transfer',
    accountId: 'checking1',
  },
  {
    _id: 'transaction3',
    name: 'Figma',
    paymentChannel: 'Card',
    type: 'debit',
    amount: 18.99,
    status: 'processing',
    date: 'Tue 11:00am',
    category: 'subscription',
    accountId: 'savings2',
  },
  {
    _id: 'transaction4',
    name: 'Sam Sodje',
    paymentChannel: 'Bank Transfer',
    type: 'credit',
    amount: 150000,
    status: 'declined',
    date: 'Mon 2:30pm',
    category: 'transfer',
    accountId: 'savings2',
  },
  {
    _id: 'transaction5',
    name: 'Apple',
    paymentChannel: 'card',
    type: 'debit',
    amount: 150,
    status: 'success',
    date: 'Sun 8:00pm',
    category: 'subscription',
    accountId: 'checking1',
  },
  {
    _id: 'transaction6',
    name: 'Spotify',
    paymentChannel: 'card',
    type: 'debit',
    amount: 15,
    status: 'processing',
    date: 'Wed 1:00pm',
    category: 'subscription',
    accountId: 'savings2',
  },
  {
    _id: 'transaction7',
    name: 'James Johnson',
    paymentChannel: 'Bank Transfer',
    type: 'credit',
    amount: 15,
    status: 'success',
    date: 'Sat 1:00pm',
    category: 'transfer',
    accountId: 'checking1',
  },
  {
    _id: 'transaction8',
    name: 'Microsoft',
    paymentChannel: 'card',
    type: 'debit',
    amount: 205.18,
    status: 'processing',
    date: 'Wed 1:00pm',
    category: 'subscription',
    accountId: 'savings2',
  },
  {
    _id: 'transaction9',
    name: 'Spotify',
    paymentChannel: 'card',
    type: 'debit',
    amount: 15,
    status: 'processing',
    date: 'Wed 1:00pm',
    category: 'subscription',
    accountId: 'checking1',
  },
  {
    _id: 'transaction10',
    name: 'Alexa Doe',
    paymentChannel: 'Bank Transfer',
    type: 'credit',
    amount: 100,
    status: 'success',
    date: 'Tue 3:00pm',
    category: 'transfer',
    accountId: 'checking1',
  },
  {
    _id: 'transaction11',
    name: 'Figma',
    paymentChannel: 'Card',
    type: 'debit',
    amount: 18.99,
    status: 'processing',
    date: 'Tue 11:00am',
    category: 'subscription',
    accountId: 'savings2',
  },
  {
    _id: 'transaction12',
    name: 'Sam Sodje',
    paymentChannel: 'Bank Transfer',
    type: 'credit',
    amount: 150000,
    status: 'declined',
    date: 'Mon 2:30pm',
    category: 'transfer',
    accountId: 'savings2',
  },
  {
    _id: 'transaction13',
    name: 'Apple',
    paymentChannel: 'card',
    type: 'debit',
    amount: 150,
    status: 'success',
    date: 'Sun 8:00pm',
    category: 'subscription',
    accountId: 'checking1',
  },
  {
    _id: 'transaction14',
    name: 'Spotify',
    paymentChannel: 'card',
    type: 'debit',
    amount: 15,
    status: 'processing',
    date: 'Wed 1:00pm',
    category: 'subscription',
    accountId: 'savings2',
  },
  {
    _id: 'transaction15',
    name: 'James Johnson',
    paymentChannel: 'Bank Transfer',
    type: 'credit',
    amount: 15,
    status: 'success',
    date: 'Sat 1:00pm',
    category: 'transfer',
    accountId: 'checking1',
  },
  {
    _id: 'transaction16',
    name: 'Microsoft',
    paymentChannel: 'card',
    type: 'debit',
    amount: 205.18,
    status: 'processing',
    date: 'Wed 1:00pm',
    category: 'subscription',
    accountId: 'savings2',
  },
];

export const accounts = [
  {
    _id: 'checking1',
    name: 'Checking Account',
    availableBalance: 5000,
    currentBalance: 8000,
    transactionHistory: {},
    cards: {},
  },
  {
    _id: 'savings2',
    name: 'Savings Account',
    availableBalance: 3000,
    currentBalance: 10000,
    transactionHistory: {},
    cards: {},
  },
];
